name: LobbyCommand
main: AleoTV\lobbymain
version: 1.0
api: [3.0.0,4.0.0]
author: AleoTV

commands:
  Heal:
   description: "Heile dich mit /heal"
   permissions: heal.command
 permissions:
   day.command:
    default: true