name: LobbyCommand
main: AleoTV\main
version: 1.1
api: [3.0.0,4.0.0]
author: AleoTV
commands:

discord:
    description: "ยง9Discord Command"
    usage: "/dc"
  heal:
    description: "Heile dich."
    usage: "/heal"
  cb1:
    description: "Bringt dich zum CB1."
    usage: "/cb1"
  author:
    description: "Um den Author kennen zu lernen."
    usage: "/author"
  
