name: LobbyCommand
main: AleoTV\lobbymain
version: 1.0
api: [3.0.0,4.0.0]
author: AleoTV

commands:
  discord:
    description: "ยง9Discord Command"
    usage: "/dc"
  heal:
    description: "Heile dich."
    usage: "/heal"
  cb1:
    description: "Bringt dich zum CB1."
    usage: "/cb1"
  author:
    description: "Um den Developer kennen zu lernen."
    usage: "/author"

